#!/usr/bin/env python
"""Build author and submission-system metadata templates.

Author: SheafSignal contributors
Date: 2026-04-30
Purpose: separate author-owned submission metadata from the reproducible
SheafSignal analysis package.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


AUTHOR_COLUMNS = [
    "author_order",
    "given_names",
    "family_names",
    "email",
    "orcid",
    "affiliation_id",
    "corresponding_author",
    "credit_roles",
    "conflict_of_interest_statement",
    "status",
]

AFFILIATION_COLUMNS = [
    "affiliation_id",
    "institution",
    "department",
    "city",
    "country",
    "status",
]

METADATA_CHECKLIST_ROWS = [
    {
        "item": "author_names_and_order",
        "owner": "authors",
        "status": "tbd_by_authors",
        "required_action": "Fill AUTHOR_METADATA_TEMPLATE.tsv and confirm author order.",
    },
    {
        "item": "affiliations",
        "owner": "authors",
        "status": "tbd_by_authors",
        "required_action": "Fill AFFILIATIONS_TEMPLATE.tsv.",
    },
    {
        "item": "corresponding_author",
        "owner": "authors",
        "status": "tbd_by_authors",
        "required_action": "Mark corresponding_author=true for at least one author.",
    },
    {
        "item": "credit_contributions",
        "owner": "authors",
        "status": "tbd_by_authors",
        "required_action": "Fill AUTHOR_CONTRIBUTIONS_CREDIT_TEMPLATE.tsv.",
    },
    {
        "item": "competing_interests",
        "owner": "authors",
        "status": "tbd_by_authors",
        "required_action": "Replace TBD in COMPETING_INTERESTS_TEMPLATE.md.",
    },
    {
        "item": "data_and_code_availability",
        "owner": "analysis_lead",
        "status": "pending_zenodo_doi",
        "required_action": "Finalize Zenodo DOI and GitHub public release URL.",
    },
]


def _write_text_atomic(path: Path, text: str) -> None:
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(text, encoding="utf-8")
    tmp_path.replace(path)


def _write_table_atomic(path: Path, table: pd.DataFrame) -> None:
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    table.to_csv(tmp_path, sep="\t", index=False)
    tmp_path.replace(path)


def author_template() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "author_order": 1,
                "given_names": "TBD",
                "family_names": "TBD",
                "email": "TBD",
                "orcid": "TBD",
                "affiliation_id": "A1",
                "corresponding_author": "TBD",
                "credit_roles": "Conceptualization; Methodology; Software; Formal analysis; Writing - original draft",
                "conflict_of_interest_statement": "TBD",
                "status": "tbd_by_authors",
            }
        ],
        columns=AUTHOR_COLUMNS,
    )


def affiliation_template() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "affiliation_id": "A1",
                "institution": "TBD",
                "department": "TBD",
                "city": "TBD",
                "country": "TBD",
                "status": "tbd_by_authors",
            }
        ],
        columns=AFFILIATION_COLUMNS,
    )


def credit_template() -> pd.DataFrame:
    roles = [
        "Conceptualization",
        "Methodology",
        "Software",
        "Formal analysis",
        "Investigation",
        "Data curation",
        "Writing - original draft",
        "Writing - review and editing",
        "Supervision",
        "Funding acquisition",
    ]
    return pd.DataFrame(
        [
            {
                "credit_role": role,
                "assigned_authors": "TBD",
                "status": "tbd_by_authors",
            }
            for role in roles
        ]
    )


def metadata_checklist() -> pd.DataFrame:
    return pd.DataFrame(METADATA_CHECKLIST_ROWS)


def competing_interests_template() -> str:
    return """# Competing Interests Statement Template

TBD.

Replace this section before submission with one of:

- The authors declare no competing interests.
- The following competing interests are declared: ...

This file is author-owned metadata. It must not be inferred from the analysis
pipeline.
"""


def ethics_data_use_statement() -> str:
    return """# Ethics And Data Use Statement Draft

This SheafSignal benchmark uses public processed scRNA-seq and spatial
transcriptomics datasets listed in `metadata/datasets.tsv`. No new human
participant data were generated by this computational analysis.

Raw public datasets remain subject to their original repository terms,
licenses, and controlled-access boundaries. The repository must not redistribute
controlled-access raw reads or private clinical metadata.

TBD by authors before submission: confirm whether the manuscript requires an
institutional exemption statement or local ethics wording.
"""


def github_release_instructions() -> str:
    return """# GitHub Public Release Instructions

## Upload Target

- Source/code archive: `release/archives/sheafsignal_github_release.zip`
- Archive checksum: see `release/archive_manifest.tsv`
- Large processed benchmark objects: upload to Zenodo, not GitHub

## Steps

1. Create or select the public GitHub repository for SheafSignal.
2. Upload the repository source files or unpack
   `release/archives/sheafsignal_github_release.zip`.
3. Confirm `.gitignore` excludes raw data, processed large matrices, and local
   archives.
4. Create a versioned release tag such as `v0.1.0`.
5. Link the Zenodo DOI in README, `metadata/datasets.tsv`, and the manuscript
   data availability statement.
6. Re-run:

```bash
python scripts/release_audit.py
python scripts/check_final_submission_blockers.py
```

## Boundary

Do not publish private clinical data, controlled-access raw reads, local
credentials, or generated archives that are intentionally ignored by Git.
"""


def build_templates(output_dir: Path, release_dir: Path) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    release_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "authors": output_dir / "AUTHOR_METADATA_TEMPLATE.tsv",
        "affiliations": output_dir / "AFFILIATIONS_TEMPLATE.tsv",
        "credit": output_dir / "AUTHOR_CONTRIBUTIONS_CREDIT_TEMPLATE.tsv",
        "metadata_checklist": output_dir / "SUBMISSION_SYSTEM_METADATA_CHECKLIST.tsv",
        "competing_interests": output_dir / "COMPETING_INTERESTS_TEMPLATE.md",
        "ethics_data_use": output_dir / "ETHICS_AND_DATA_USE_STATEMENT.md",
        "github_release": release_dir / "GITHUB_RELEASE_INSTRUCTIONS.md",
    }
    _write_table_atomic(outputs["authors"], author_template())
    _write_table_atomic(outputs["affiliations"], affiliation_template())
    _write_table_atomic(outputs["credit"], credit_template())
    _write_table_atomic(outputs["metadata_checklist"], metadata_checklist())
    _write_text_atomic(outputs["competing_interests"], competing_interests_template())
    _write_text_atomic(outputs["ethics_data_use"], ethics_data_use_statement())
    _write_text_atomic(outputs["github_release"], github_release_instructions())
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="manuscript/submission_metadata")
    parser.add_argument("--release-dir", default="release")
    args = parser.parse_args(argv)

    outputs = build_templates(Path(args.output_dir), Path(args.release_dir))
    for path in outputs.values():
        print(f"wrote {path.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
